FROM python:3.7-stretch

MAINTAINER Gilles Bodart <gillesbodart@users.noreply.github.com>
 
RUN apt-get -qq -y update
RUN apt-get -qq -y upgrade
RUN apt-get -qq -y install \
        gcc \
        g++ \
        wget \
        curl \
        git \
        make \
        sudo \
        bash-completion \
        tree \
        vim

# Use C.UTF-8 locale to avoid issues with ASCII encoding
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Install any needed packages specified in requirements.txt
WORKDIR /app
COPY ./docker/requirements.txt /app/requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt --verbose

# Download LASER from FB and install
RUN git clone https://github.com/facebookresearch/LASER.git
ENV LASER /app/LASER
WORKDIR $LASER  
RUN bash ./install_models.sh
RUN bash ./install_external_tools.sh
COPY ./docker/decode.py $LASER/tasks/embed/decode.py

# run tests
WORKDIR /app
RUN echo "Hello World" > test.txt
RUN $LASER/tasks/embed/embed.sh test.txt en test_embed.raw
RUN python $LASER/tasks/embed/decode.py test_embed.raw

# copy only at the end so that code updates do not require new slow build
COPY ./docker /app  

EXPOSE 8099 
CMD ["python", "app.py"] 
